### PR TITLE
Build on GitHub actions.

### PR DESCRIPTION
**Pull request by athas**
* Does not build every single package, but only the one I arbitrarily decided are probably the most important.  It does build at least one version of LLVM, so it's not like I only picked the small ones.

* Builds on GitHub-provided VMs.  This takes several hours.  GitHub Actions provides some way of supplying your own "runners" (machines), but I don't know the technical details.

* **Does not yet upload anything to Cachix**.  I think this is easy to add, but it involves creating the caches and somehow installing the keys so that the GitHub Actions can access them.

### CODE REVIEW

**Comment by athas** [comment]
[This run](https://github.com/athas/nixos-rocm/runs/761521839?check_suite_focus=true) shows that it takes 40 minutes to build `rocm-llvm`, another 40 minutes to build `rocm-clang`, another 4 minutes to get OpenCL, and then three and a half hours to get `rocblas`.

**Comment by acowley** [comment]
Wow, that actually seems great, right?! There's a 6 hour limit on individual jobs, but that seems to leave us some overhead here. I'd like to add `hip-clang` to the job set, but that's really it for now. Are you going to look into creating a `nixos-rocm` cachix cache and the key stuff, or do you want me to do that?

Thank you so much for taking this on!

**Comment by acowley** [comment]
Oh, one thing we should keep an eye on is that the cachix free tier has a 10GB storage cap. After that, it enforces an LRU eviction policy. Looking at my system, `hip-clang` has a 1GB closure size, so we're probably fine, but we'll likely get to within sight of that limit if we get up to building `pytorch`. This also of course limits how many builds we can have in the cache. I think that's not critical by any means, but something we should make clear to users unless we can get access to more cachix storage.

**Comment by athas** [comment]
I think it's easiest for you to set up the Cachix bit, since it requires repository administrative access.

Unfortunately, the rocblas build seems to sometimes take the entire job time past 6 hours, which gets it killed by GitHub.  I'll try to handle it by splitting the workflow into multiple jobs.  This would work better once we have Cachix running, and later jobs can depend on work done by previous jobs.

**Comment by athas** [comment]
Splitting worked fine.

**Comment by acowley** [comment]
It looks great to me. Are you happy to merge?

**Comment by athas** [comment]
Yes.

**Comment by athas** [comment]
You should then set up Cachix as described here: https://github.com/marketplace/actions/cachix

I did it for another repository of mine, and it's really quite easy.

**Comment by acowley** [comment]
Does LLVM get built again as part of the `rocblas` job, or is it able to make use of the existing build from the opencl part?

I think I'm seeing the `rocblas` job rebuild LLVM, but I've already noticed some oddities with the live log display, so it may be a bug there.

**Comment by acowley** [comment]
Yeah, [this](https://stackoverflow.com/questions/57498605/github-actions-share-workspace-artifacts-between-jobs) suggests that we'd need to upload/download the products of earlier jobs if we want later jobs to use them.

Cachix will presumably do this for us.

**Comment by acowley** [comment]
With cachix, the rocBLAS 3.5.0 build only took 33 minutes! I'm not sure if everything's working properly, but, if so, that seems great.

Something I don't know is how we could report the `nixpkgs` revision used by CI. We could pin `nixpkgs` ourselves, but then we'd lose the rolling release opportunity CI gives us unless we have an automated PR that advances `nixpkgs`. We could write our own thing to somehow emit this information as part of the build. But I'd hope that there is an existing solution to this. Any thoughts?

**Comment by athas** [comment]
Since the job runs daily, the odds are good that it will always be current relative to the newest unstable.  I don't know if we could be more precise than that.

**Pull request merged**
