### PR TITLE
ROCm 3.3.x

### PR DESCRIPTION
**Pull request by acowley**
Working:
- OpenCL
- hcc
- HIP
- hip-clang

Broken:
- tensorflow (1 and 2)
- pytorch

Tensorflow segfaults in rocBLAS, so that library is possibly broken.

### CODE REVIEW

**Comment by athas** [comment]
This works fine on my system.

**Comment by athas** [comment]
I am also very pleased to report that #28 is no longer a problem.  I don't know whether this is because of changes in ROCm or Mesa.

**Comment by acowley** [comment]
@athas Thank you so much for confirming that this works for you, and PHEW! 😅 on that OpenGL issue going away. Looking into that was like staring into the abyss, so I am relieved that it went away on its own.

**Comment by athas** [comment]
I strongly suspect that OpenGL issue will come back intermittently.  Loading two instances of LLVM into the same process cannot be healthy for anyone.

**Comment by acowley** [comment]
I agree, but I can't figure out two things:

- I think both of us tried rebuilding Mesa with the LLVM used for rocm-opencl-runtime, and it didn't help.
- Shouldn't other ROCm users be running into this? AMD has a... festive... attitude toward LLVM forks, so I'd expect this to be widespread if there is indeed a fundamental problem.

I may have done something wrong when I tried this since OpenGL is one of those special things on NixOS. So if this comes up again, I'll give it another shot.

**Comment by athas** [comment]
> I think both of us tried rebuilding Mesa with the LLVM used for rocm-opencl-runtime, and it didn't help.

I couldn't figure out how to do this.  But do note that AFAIK, you need to reboot after doing the rebuild, since the problem is in the OpenGL *driver* that gets made available in `/var/run/opengl-driver`.

> Shouldn't other ROCm users be running into this? AMD has a... festive... attitude toward LLVM forks, so I'd expect this to be widespread if there is indeed a fundamental problem.

[They are](https://github.com/RadeonOpenCompute/ROCm/issues/992#issuecomment-600092629).

**Pull request merged**
