### PR TITLE
Update to 1.7.1 and housekeeping

### PR DESCRIPTION
**Pull request by acowley**
I can break these down into separate PRs if needed, but I think each commit is fairly well self-contained.

### CODE REVIEW

**Comment by pl-semiotics** [comment]
Sorry for the delay---I thought I had already merged this. This all looks great, thank you for the updates/improvements!

**Comment by acowley** [comment]
No worries! I’ve packaged a somewhat broad swath of rocm-related things at this point. Do you think it’s worth consolidating them here (or elsewhere), or should we keep the core pieces you have here separate?

On the one hand, what you have here is distinctly central, so may be worth keeping distinct from the somewhat haphazard array of things AMD has started porting. On the other, having a rocm overlay that attempts to include everything might be neat. Things I’ve gotten working include `hcc`, `hip`, `rocblas`, and more. Unfortunately, the higher level things like TensorFlow and caffe do not yet work.

**Comment by pl-semiotics** [comment]
@acowley 

Oh dear, I seem to have not gotten notified about this comment, maybe due to the PR being merged. Sorry for the delay in response. If you're still open to combining the overlays, I think that is a great idea---there isn't much of a downside to having more software available than one actually uses, and it would be great to have one place where new users can be pointed that will include a large portion of the interesting things that can be done with ROCm.

We could also create a small GH org with a new combined repo somewhere, since I am not sure how much time/effort I will have to put into ROCm things right now (as I don't have super pressing use cases for much more), so I feel a bit bad keeping the repo under my GH account when a large portion of it would be your work.

**Comment by acowley** [comment]
If you're for it, let's do an organization; I hope we can get other people to chip in. AMD's approach is extremely focused on Ubuntu 16.04. Their docker containers work great with what you have here, so that's great, but building things to run more natively in NixOS involves a lot of path patches. I think I have their caffe2 port working, but tensorflow is brutal with the bazel layers adding to the spread of hard-coded installation paths.

**Pull request merged**
